spring.datasource.url=jdbc:postgresql://localhost:5432/database
spring.datasource.username=12345
spring.datasource.password=12346

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8099